package ydb

import (
	"context"
	"database/sql"
	"fmt"
	nurl "net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/dhui/dktest"
	"github.com/docker/docker/api/types/mount"
	"github.com/docker/go-connections/nat"
	"github.com/golang-migrate/migrate/v4"
	dt "github.com/golang-migrate/migrate/v4/database/testing"
	"github.com/golang-migrate/migrate/v4/dktesting"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	ydbsdk "github.com/ydb-platform/ydb-go-sdk/v3"
)

const (
	defaultPort = 2135 // TLS gRPC port
	defaultHost = "localhost"
)

// certsDir is the absolute path to ydb_certs/ — it is bind-mounted into the
// container as /ydb_certs and holds the certs generated by gen-ca.sh.
// YDB expects ca.pem, cert.pem, and key.pem at the root of /ydb_certs.
// dataDir is for YDB persistent storage.
// opts and specs are populated in init() after these paths are known.
var (
	certsDir string
	dataDir  string
	opts     dktest.Options
	specs    []dktesting.ContainerSpec
)

func init() {
	wd, err := os.Getwd()
	if err != nil {
		panic("ydb_test: cannot get working directory: " + err.Error())
	}
	certsDir = filepath.Join(wd, "ydb_certs")
	dataDir = filepath.Join(wd, "ydb_data")

	for _, dir := range []string{certsDir, dataDir} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			panic("ydb_test: cannot create directory " + dir + ": " + err.Error())
		}
	}

	// Clear ydb_data/ so the container always reinitialises from the fresh
	// certs in ydb_certs/ rather than reusing stale state from a previous run.
	if err := os.RemoveAll(dataDir); err != nil {
		panic("ydb_test: cannot clear ydb_data: " + err.Error())
	}
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		panic("ydb_test: cannot recreate ydb_data: " + err.Error())
	}

	// Run gen-ca.sh inside ydb_certs/ so it writes ca.pem, cert.pem, key.pem
	// directly there — those files are what the container expects at /ydb_certs.
	if err := generateCerts(certsDir); err != nil {
		panic("ydb_test: cannot generate TLS certs: " + err.Error())
	}

	opts = dktest.Options{
		// Set hostname to "localhost" so YDB discovery returns "localhost" as the
		// node address, which is resolvable from the host machine.
		Hostname:     "localhost",
		PortRequired: true,
		// Use fixed host ports matching the reference docker run command.
		PortBindings: nat.PortMap{
			nat.Port("2135/tcp"): []nat.PortBinding{{HostPort: "2135"}},
			nat.Port("2136/tcp"): []nat.PortBinding{{HostPort: "2136"}},
			nat.Port("8765/tcp"): []nat.PortBinding{{HostPort: "8765"}},
		},
		// YDB takes ~30s to be fully ready; allow up to 3 minutes total.
		ReadyTimeout: 3 * time.Minute,
		Timeout:      3 * time.Minute,
		// Bind-mount ydb_certs (TLS certs) and ydb_data (persistent storage)
		// so YDB always reads the freshly generated certs from the host.
		Mounts: []mount.Mount{
			{
				Type:   mount.TypeBind,
				Source: certsDir,
				Target: "/ydb_certs",
			},
			{
				Type:   mount.TypeBind,
				Source: dataDir,
				Target: "/ydb_data",
			},
		},
		Env: map[string]string{
			"GRPC_TLS_PORT":         "2135",
			"GRPC_PORT":             "2136",
			"MON_PORT":              "8765",
			"YDB_DEFAULT_LOG_LEVEL": "NOTICE",
		},
		ReadyFunc:      isReady,
		CleanupTimeout: 3 * time.Minute,
	}
	specs = []dktesting.ContainerSpec{
		{ImageName: "cr.yandex/yc/yandex-docker-local-ydb:latest", Options: opts},
	}
}

// generateCerts runs gen-ca.sh with its working directory set to dir so that
// it writes ca.pem, cert.pem, and key.pem directly into dir.
// It clears any existing cert files first to ensure the container and the
// Go client always use the same freshly generated CA.
func generateCerts(dir string) error {
	// Remove stale cert files so gen-ca.sh always produces a fresh set that
	// matches what the Go client will trust.
	for _, f := range []string{"ca.pem", "ca-key.pem", "cert.pem", "key.pem"} {
		_ = os.Remove(filepath.Join(dir, f))
	}

	wd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getwd: %w", err)
	}
	script := filepath.Join(wd, "gen-ca.sh")
	cmd := exec.Command("sh", script)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gen-ca.sh: %w\n%s", err, out)
	}
	return nil
}

func ydbConnectionString(host, port string, options ...string) string {
	// grpcs:// using the CA certificate produced by gen-ca.sh (ydb_certs/ca.pem).
	// go_balancer=single skips YDB SDK node discovery to avoid resolving
	// Docker-internal hostnames from the host.
	baseOpts := []string{
		"go_balancer=single",
		"x-tls-certificate-file=" + filepath.Join(certsDir, "ca.pem"),
	}
	baseOpts = append(baseOpts, options...)
	return fmt.Sprintf("grpcs://%s:%s/local?%s", host, port, strings.Join(baseOpts, "&"))
}

func isReady(ctx context.Context, c dktest.ContainerInfo) bool {
	_, port, err := c.Port(defaultPort)
	if err != nil {
		return false
	}

	caPEM, err := os.ReadFile(filepath.Join(certsDir, "ca.pem"))
	if err != nil {
		return false
	}
	cert, err := parsePEMCertificate(caPEM)
	if err != nil {
		return false
	}

	dsn := fmt.Sprintf("grpcs://%s:%s/local?go_balancer=single", defaultHost, port)

	// Use a short per-attempt timeout so dktest can keep retrying until its
	// own 3-minute deadline expires.
	attemptCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	nativeDriver, err := ydbsdk.Open(attemptCtx, dsn, ydbsdk.WithCertificate(cert))
	if err != nil {
		return false
	}
	defer nativeDriver.Close(ctx) //nolint:errcheck

	connector, err := ydbsdk.Connector(nativeDriver,
		ydbsdk.WithAutoDeclare(),
		ydbsdk.WithPositionalArgs(),
	)
	if err != nil {
		return false
	}

	db := sql.OpenDB(connector)
	defer db.Close() //nolint:errcheck

	// A plain Ping only checks that gRPC is up. YDB storage pools are
	// initialised asynchronously and may not be ready for DDL immediately
	// after gRPC starts. Probe by actually executing a DDL statement; if YDB
	// reports "database doesn't have storage pools" we return false and let
	// dktest retry.
	const probeTable = `_migrate_probe`
	ddlCtx := ydbsdk.WithQueryMode(attemptCtx, ydbsdk.SchemeQueryMode)
	_, err = db.ExecContext(ddlCtx,
		"CREATE TABLE `"+probeTable+"` (id Int64 NOT NULL, PRIMARY KEY (id))")
	if err != nil {
		// "storage pools" means YDB is still bootstrapping — keep retrying.
		if strings.Contains(err.Error(), "storage pools") ||
			strings.Contains(err.Error(), "Unavailable") ||
			strings.Contains(err.Error(), "transport") {
			return false
		}
		// Any other DDL error (e.g. table already exists) means YDB is up.
	}

	// Clean up the probe table (best-effort).
	_, _ = db.ExecContext(ddlCtx, "DROP TABLE `"+probeTable+"`")

	return true
}

func Test(t *testing.T) {
	t.Run("test", test)
	t.Run("testMigrate", testMigrate)
	t.Run("testMultipleStatementsInMultiStatementMode", testMultipleStatementsInMultiStatementMode)
	t.Run("testFilterCustomQuery", testFilterCustomQuery)
	t.Run("testMigrationTableOption", testMigrationTableOption)
	t.Run("testLock", testLock)
	t.Run("testWithInstanceConcurrent", testWithInstanceConcurrent)

	t.Cleanup(func() {
		for _, spec := range specs {
			t.Log("Cleaning up ", spec.ImageName)
			if err := spec.Cleanup(); err != nil {
				t.Error("Error removing ", spec.ImageName, "error:", err)
			}
		}
		// Remove generated certs and persistent data directories.
		for _, dir := range []string{certsDir, dataDir} {
			if err := os.RemoveAll(dir); err != nil {
				t.Errorf("cleanup: failed to remove %s: %v", dir, err)
			}
		}
	})
}

func test(t *testing.T) {
	dktesting.ParallelTest(t, specs, func(t *testing.T, c dktest.ContainerInfo) {
		_, port, err := c.Port(defaultPort)
		if err != nil {
			t.Fatal(err)
		}

		addr := ydbConnectionString(defaultHost, port)
		y := &YDB{}
		d, err := y.Open(addr)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := d.Close(); err != nil {
				t.Error(err)
			}
		}()
		dt.Test(t, d, []byte("SELECT 1"))
	})
}

func testMigrate(t *testing.T) {
	dktesting.ParallelTest(t, specs, func(t *testing.T, c dktest.ContainerInfo) {
		_, port, err := c.Port(defaultPort)
		if err != nil {
			t.Fatal(err)
		}

		addr := ydbConnectionString(defaultHost, port)
		y := &YDB{}
		d, err := y.Open(addr)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := d.Close(); err != nil {
				t.Error(err)
			}
		}()
		m, err := migrate.NewWithDatabaseInstance("file://./examples/migrations", "ydb", d)
		if err != nil {
			t.Fatal(err)
		}
		dt.TestMigrate(t, m)
	})
}

func testMultipleStatementsInMultiStatementMode(t *testing.T) {
	dktesting.ParallelTest(t, specs, func(t *testing.T, c dktest.ContainerInfo) {
		_, port, err := c.Port(defaultPort)
		if err != nil {
			t.Fatal(err)
		}

		addr := ydbConnectionString(defaultHost, port, "x-multi-statement=true")
		y := &YDB{}
		d, err := y.Open(addr)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := d.Close(); err != nil {
				t.Error(err)
			}
		}()

		// Create two tables in a single multi-statement migration
		err = d.Run(strings.NewReader(
			"CREATE TABLE multi_a (id Int64 NOT NULL, PRIMARY KEY (id));" +
				"CREATE TABLE multi_b (id Int64 NOT NULL, PRIMARY KEY (id));",
		))
		if err != nil {
			t.Fatalf("expected err to be nil, got %v", err)
		}

		// Verify second table exists by inserting into it
		ydbDriver := d.(*YDB)
		if _, err := ydbDriver.db.ExecContext(context.Background(),
			"UPSERT INTO multi_b (id) VALUES (1)"); err != nil {
			t.Fatalf("expected table multi_b to exist, got error: %v", err)
		}
	})
}

func testFilterCustomQuery(t *testing.T) {
	dktesting.ParallelTest(t, specs, func(t *testing.T, c dktest.ContainerInfo) {
		_, port, err := c.Port(defaultPort)
		if err != nil {
			t.Fatal(err)
		}

		addr := ydbConnectionString(defaultHost, port, "x-custom=foobar")
		y := &YDB{}
		d, err := y.Open(addr)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := d.Close(); err != nil {
				t.Error(err)
			}
		}()
	})
}

func testMigrationTableOption(t *testing.T) {
	dktesting.ParallelTest(t, specs, func(t *testing.T, c dktest.ContainerInfo) {
		_, port, err := c.Port(defaultPort)
		if err != nil {
			t.Fatal(err)
		}

		addr := ydbConnectionString(defaultHost, port, "x-migrations-table=custom_migrations")
		y := &YDB{}
		d, err := y.Open(addr)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := d.Close(); err != nil {
				t.Error(err)
			}
		}()

		// Verify the custom migrations table is used by checking the driver config
		ydbDriver := d.(*YDB)
		if ydbDriver.config.MigrationsTable != "custom_migrations" {
			t.Fatalf("expected migrations table to be 'custom_migrations', got '%s'",
				ydbDriver.config.MigrationsTable)
		}

		// Ensure the table was actually created by setting a version
		if err := d.SetVersion(1, false); err != nil {
			t.Fatal(err)
		}
		version, dirty, err := d.Version()
		if err != nil {
			t.Fatal(err)
		}
		if version != 1 {
			t.Fatalf("expected version 1, got %d", version)
		}
		if dirty {
			t.Fatal("expected dirty to be false")
		}
	})
}

func testLock(t *testing.T) {
	dktesting.ParallelTest(t, specs, func(t *testing.T, c dktest.ContainerInfo) {
		_, port, err := c.Port(defaultPort)
		if err != nil {
			t.Fatal(err)
		}

		addr := ydbConnectionString(defaultHost, port)
		y := &YDB{}
		d, err := y.Open(addr)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := d.Close(); err != nil {
				t.Error(err)
			}
		}()

		ydbDriver := d.(*YDB)

		// Lock, unlock, lock, unlock cycle
		err = ydbDriver.Lock()
		if err != nil {
			t.Fatal(err)
		}

		// Locking again should fail
		err = ydbDriver.Lock()
		if err == nil {
			t.Fatal("expected error when locking twice, got nil")
		}

		err = ydbDriver.Unlock()
		if err != nil {
			t.Fatal(err)
		}

		// Should be able to lock again after unlock
		err = ydbDriver.Lock()
		if err != nil {
			t.Fatal(err)
		}

		err = ydbDriver.Unlock()
		if err != nil {
			t.Fatal(err)
		}
	})
}

func testWithInstanceConcurrent(t *testing.T) {
	dktesting.ParallelTest(t, specs, func(t *testing.T, c dktest.ContainerInfo) {
		_, port, err := c.Port(defaultPort)
		if err != nil {
			t.Fatal(err)
		}

		const concurrency = 30

		// Must use native driver + connector path (same as Open()) so that
		// TLS and WithAutoDeclare() are properly configured.
		connStr := ydbConnectionString(defaultHost, port)
		// Strip x-* params before passing to ydb.Open (mirrors what Open() does).
		purl, err := nurl.Parse(connStr)
		if err != nil {
			t.Fatal(err)
		}

		pemBytes, err := os.ReadFile(filepath.Join(certsDir, "ca.pem"))
		if err != nil {
			t.Fatalf("cannot read ca.pem: %v", err)
		}
		cert, err := parsePEMCertificate(pemBytes)
		if err != nil {
			t.Fatalf("cannot parse ca.pem: %v", err)
		}

		ctx := context.Background()
		nativeDriver, err := ydbsdk.Open(ctx, migrate.FilterCustomQuery(purl).String(),
			ydbsdk.WithCertificate(cert),
		)
		if err != nil {
			t.Fatal(err)
		}
		defer func() { _ = nativeDriver.Close(ctx) }()

		connector, err := ydbsdk.Connector(nativeDriver,
			ydbsdk.WithAutoDeclare(),
			ydbsdk.WithPositionalArgs(),
		)
		if err != nil {
			t.Fatal(err)
		}

		db := sql.OpenDB(connector)
		defer func() {
			if err := db.Close(); err != nil {
				t.Error(err)
			}
		}()

		db.SetMaxIdleConns(concurrency)
		db.SetMaxOpenConns(concurrency)

		var wg sync.WaitGroup
		defer wg.Wait()

		wg.Add(concurrency)
		for i := 0; i < concurrency; i++ {
			go func(i int) {
				defer wg.Done()
				_, err := WithInstance(db, &Config{
					DatabaseName: "/local",
				})
				if err != nil {
					t.Errorf("process %d error: %s", i, err)
				}
			}(i)
		}
	})
}
