version: "2"
linters:
  enable:
    - goconst
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: redundant-build-tag
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: G104
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
