# options for analysis running
run:
  tests: false

output:
  print-issued-lines: false

linters:
  enable:
    #- golint
    - interfacer
    - unconvert
    #- dupl
    - goconst
    - gofmt
    - misspell
    - maligned
    - unparam
    - nakedret
    - prealloc
    #- gosec
linters-settings:
  misspell:
    locale: US
issues:
  max-same: 0
  max-per-linter: 0
  exclude-use-default: false
  exclude:
    # gosec: Duplicated errcheck checks
    - G104