version: "2"

run:
  timeout: 5m

linters:
  enable:
    - unconvert
    - goconst
    - gofmt
    - misspell
    - unparam
    - nakedret
    - prealloc
    - revive
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: redundant-build-tag
