// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packr

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "fbf96a81b982c57542097cbde0fe4f60"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"4e7f47c073078fee04d5d733cf114944": "1f8b08000000000000ff325148c92fcfe302040000ffff33bc0e8307000000",
		"82680397a42117abddec762ef20a4b85": "1f8b08000000000000ff325748c92fcfe302040000ffffaea6e6b207000000",
		"b4d90c024f26d6736dcb2325c240db22": "1f8b08000000000000ff3251282de002040000ffff367c61af05000000",
		"bed54dd91e7d815421cb6bc257fca526": "1f8b08000000000000ff3257282de002040000ffffe606c1e805000000",
		"e2163ac25bb372188cd5f626b8a35eec": "1f8b08000000000000ff3256282de002040000ffff26a0411d05000000",
		"f14454f3ae9c5307e61f1b5ea5bf30fa": "1f8b08000000000000ff325548c92fcfe302040000ffff87b7792507000000",
		"f8330ef3b66dd8c0276aab257c951696": "1f8b08000000000000ff325448c92fcf03040000ffff88159e8206000000",
		"f883d0a95999cbc05a306b6de0004da1": "1f8b08000000000000ff3254282d00040000ffffb7fad35304000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("testdata", ".")
		b.SetResolver("migrations/1_foobar.down.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "f8330ef3b66dd8c0276aab257c951696"})
		b.SetResolver("migrations/1_foobar.up.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "f883d0a95999cbc05a306b6de0004da1"})
		b.SetResolver("migrations/3_foobar.up.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "e2163ac25bb372188cd5f626b8a35eec"})
		b.SetResolver("migrations/4_foobar.down.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "4e7f47c073078fee04d5d733cf114944"})
		b.SetResolver("migrations/4_foobar.up.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "b4d90c024f26d6736dcb2325c240db22"})
		b.SetResolver("migrations/5_foobar.down.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "f14454f3ae9c5307e61f1b5ea5bf30fa"})
		b.SetResolver("migrations/7_foobar.down.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "82680397a42117abddec762ef20a4b85"})
		b.SetResolver("migrations/7_foobar.up.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "bed54dd91e7d815421cb6bc257fca526"})
	}()

	return nil
}()
