name: lint

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  lint:
    uses: Banno/go-shared-files/.github/workflows/lint.yml@mirai-v1
    secrets: inherit
    with:
      go-version: 1.19
